### ISSUE TITLE
Semi-Markov: Review distributions.jl file to enable semi-Markov processes

### ISSUE THREAD

**Issue by timmyfaraday** [timmyfaraday/MultiStateSystems.jl#3]
To Do:
- [x] distribution structs should be adjusted to allow for anonymous functions
- [x] pdf, cdf, ccdf should be extended to allow for calendar time input
- [x] add LogNormal distribution

**Comment by timmyfaraday** [comment]
@Glenn-sergej,

There is an issue with the log-normal distribution when units are considered, this is why I deleted it previously from the repo.
When consider a quantity in unit `u`, one expects the y-axis of the pdf to be expressed in `1/u`, so when you take the integral under the pdf, you obtain a unitless probability.

Now, consider the pdf of a log-normal distribution:

<img src="https://render.githubusercontent.com/render/math?math={\color{gray}\displaystyle {f(x) = \frac {1}{x\sigma {\sqrt {2\pi }}}}\ \exp \left(-{\frac {\left(\ln \left(x\right)-\mu \right)^{2}}{2\sigma ^{2}}}\right),}">

and consider the following input `μ=1.0 hr`, `σ=0.1 hr` and `x=2.0 hr`. It can easily be seen that the units in the exponential cancel each other out. Consequently, the unit of `f(x)` will be `1 / hr^2` rather than `1 / hr` as expected.

As far as I can see, there are no unit-related issues with the cdf or ccdf.

Is my thinking correct, how would you like to proceed?

**Comment by timmyfaraday** [comment]
@Glenn-sergej,

Exponential and Weibull distributions are commited to the branch, feel free to play around with it, and give feedback.

**Comment by Glemmers** [comment]
@timmyfaraday 

I was thinking at first that after simplification the unit within the exponential would become `log( hr )`, leading to a pdf with unit of `1 / hr`. Sadly this doesn't seem to be the case indeed...

Is it possible to consider `μ`, `σ` and the `x` within the logarithm to be without unit? Given that the user of the platform is aware that these should be scaled with respect to the x in the denominator?

**Comment by timmyfaraday** [comment]
@Glenn-sergej,

I think I'll make it unitless in the function and the unit afterwards again. 
I'll make an implementation for you to try.

**Comment by timmyfaraday** [comment]
@Glenn-sergej, 

This part of the code should be done. 
I've tested this internally, feel free to try it out.
